### ISSUE TITLE
eth-abi 0.5.0 has requirement eth-utils==0.7.*, but you'll have eth-utils 0.8.1 which is incompatible.

### ISSUE THREAD

**Issue by zdavatz** [vaguileradiaz/tinfoleak#6]
Hi

I am trying to install on Gentoo Linux, but I am constantly getting this:

`eth-abi 0.5.0 has requirement eth-utils==0.7.*, but you'll have eth-utils 0.8.1 which is incompatible.`

Will it run with 0.8.1?

**Comment by zdavatz** [comment]
Ok I managed to solve this, by uninstalling the manually installed packages that where not installed with pip.

**Comment by robertgenito** [comment]
would *love* to know which packages you manually installed/uninstalled!

**Comment by zdavatz** [comment]
sorry, no clue anymore. ;)
